os: Visual Studio 2022

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set QTDIR=C:\Qt\6.5.3\msvc2019_64
  - set QTINSTALLER=C:\Qt\Tools\QtInstallerFramework\4.6
  - set PATH=%QTDIR%\bin;%QTINSTALLER%\bin;%PATH%

build_script:
  - qmake -config release
  - nmake
  - windeployqt --release --no-translations --no-angle --no-opengl-sw release\obsautorecord.exe
  - 7z a ObsAutoRecord_win64.zip .\release\*
  - del /s /q installer\packages\com.fmeyer.obsautorecord\data
  - rmdir /s /q installer\packages\com.fmeyer.obsautorecord\data
  - move release installer\packages\com.fmeyer.obsautorecord\data
  - binarycreator --offline-only -c installer\config\config.xml -p installer\packages ObsAutoRecord_win64_setup.exe
  
artifacts:
  - path: ObsAutoRecord_win64.zip
  - path: ObsAutoRecord_win64_setup.exe

deploy:
  provider: GitHub
  auth_token:
    secure: 3BV2pxge0Mhq8LeKV/tkKPEVFQGbxx6loqMurhf8wpRzvEm0HxXJvaOaxnJweMLp
  artifact: ObsAutoRecord_win64.zip, ObsAutoRecord_win64_setup.exe
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
