"""
This is a setup.py script generated by py2applet

Usage:
    python ObsAutoRecordMacSetup.py py2app
"""

from setuptools import setup

APP = ['ObsAutoRecordMac.py']
DATA_FILES = ['record_green.ico', 'record_red.ico']
OPTIONS = {
  'argv_emulation': True,
  'iconfile': 'record_red.icns',
  'optimize': 2,
  'plist': {
    'LSUIElement': True,
  },
  'packages': ['psutil', 'rumps', 'websocket'],
}

setup(
    name="ObsAutoRecord",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
